
BASECLASSES_SOURCES += external/baseclasses/amextra.cpp external/baseclasses/amfilter.cpp external/baseclasses/amvideo.cpp external/baseclasses/arithutil.cpp external/baseclasses/combase.cpp external/baseclasses/cprop.cpp external/baseclasses/ctlutil.cpp external/baseclasses/ddmm.cpp external/baseclasses/dllentry.cpp external/baseclasses/dllsetup.cpp external/baseclasses/mtype.cpp external/baseclasses/outputq.cpp external/baseclasses/perflog.cpp external/baseclasses/pstream.cpp external/baseclasses/pullpin.cpp external/baseclasses/refclock.cpp external/baseclasses/renbase.cpp external/baseclasses/schedule.cpp external/baseclasses/seekpt.cpp external/baseclasses/source.cpp external/baseclasses/strmctl.cpp external/baseclasses/sysclock.cpp external/baseclasses/transfrm.cpp external/baseclasses/transip.cpp external/baseclasses/videoctl.cpp external/baseclasses/vtrans.cpp external/baseclasses/winctrl.cpp external/baseclasses/winutil.cpp external/baseclasses/wxdebug.cpp external/baseclasses/wxlist.cpp external/baseclasses/wxutil.cpp
LIBOGG_SOURCES += ogg/libogg/src/bitwise.c ogg/libogg/src/framing.c
LIBVORBIS_SOURCES += ogg/libvorbis/lib/analysis.c ogg/libvorbis/lib/bitrate.c ogg/libvorbis/lib/block.c ogg/libvorbis/lib/codebook.c ogg/libvorbis/lib/envelope.c ogg/libvorbis/lib/floor0.c ogg/libvorbis/lib/floor1.c ogg/libvorbis/lib/info.c ogg/libvorbis/lib/lookup.c ogg/libvorbis/lib/lpc.c ogg/libvorbis/lib/lsp.c ogg/libvorbis/lib/mapping0.c ogg/libvorbis/lib/mdct.c ogg/libvorbis/lib/psy.c ogg/libvorbis/lib/registry.c ogg/libvorbis/lib/res0.c ogg/libvorbis/lib/sharedbook.c ogg/libvorbis/lib/smallft.c ogg/libvorbis/lib/synthesis.c ogg/libvorbis/lib/vorbisenc.c ogg/libvorbis/lib/window.c
LIBTHEORA_SOURCES += ogg/libtheora/lib/analyze.c ogg/libtheora/lib/apiwrapper.c ogg/libtheora/lib/bitpack.c ogg/libtheora/lib/decapiwrapper.c ogg/libtheora/lib/decinfo.c ogg/libtheora/lib/decode.c ogg/libtheora/lib/dequant.c ogg/libtheora/lib/encapiwrapper.c ogg/libtheora/lib/encfrag.c ogg/libtheora/lib/encinfo.c ogg/libtheora/lib/encode.c ogg/libtheora/lib/encoder_disabled.c ogg/libtheora/lib/enquant.c ogg/libtheora/lib/fdct.c ogg/libtheora/lib/fragment.c ogg/libtheora/lib/huffdec.c ogg/libtheora/lib/huffenc.c ogg/libtheora/lib/idct.c ogg/libtheora/lib/info.c ogg/libtheora/lib/internal.c ogg/libtheora/lib/mathops.c ogg/libtheora/lib/mcenc.c ogg/libtheora/lib/quant.c ogg/libtheora/lib/rate.c ogg/libtheora/lib/state.c ogg/libtheora/lib/tokenize.c

SOURCES += dllmain.cpp ogg/AbstractTransformFilter.cpp ogg/AbstractTransformInputPin.cpp ogg/AbstractTransformOutputPin.cpp ogg/AutoAnxSeekTable.cpp ogg/AutoOggChainGranuleSeekTable.cpp ogg/AutoOggSeekTable.cpp ogg/BasicSeekPassThrough.cpp ogg/CircularBuffer.cpp ogg/CustomOggChainGranuleSeekTable.cpp ogg/ds_guids.cpp ogg/iBE_Math.cpp ogg/iLE_Math.cpp ogg/OggBinarySeeker.cpp ogg/OggDataBuffer.cpp ogg/OggDemuxFilter.cpp ogg/OggDemuxInputPin.cpp ogg/OggDemuxOutputPin.cpp ogg/OggFilterFactory.cpp ogg/OggGranuleSeekTable.cpp ogg/OggMuxStream.cpp ogg/OggPacket.cpp ogg/OggPacketiser.cpp ogg/OggPage.cpp ogg/OggPageHeader.cpp ogg/OggPageInterleaver.cpp ogg/OggPaginator.cpp ogg/OggPaginatorSettings.cpp ogg/OggSeekPoint.cpp ogg/OggSeekTable.cpp ogg/OGGSRecogniser.cpp ogg/OggStreamMapper.cpp ogg/StampedOggPacket.cpp ogg/StringHelper.cpp ogg/TheoraDecodeFilter.cpp ogg/TheoraDecodeInputPin.cpp ogg/TheoraDecodeOutputPin.cpp ogg/TheoraDecoder.cpp ogg/VorbisDecodeFilter.cpp ogg/VorbisDecodeInputPin.cpp ogg/VorbisDecodeOutputPin.cpp ogg/VorbisDecoder.cpp
SOURCES += $(BASECLASSES_SOURCES) $(LIBOGG_SOURCES) $(LIBVORBIS_SOURCES) $(LIBTHEORA_SOURCES)

INCFLAGS += -Iogg -Iogg/libogg/include -Iogg/libtheora/include -Iogg/libvorbis/include -Iogg/libvorbis/lib -Iexternal/baseclasses

LDLIBS += -lole32 -loleaut32 -luuid -lwinmm -lstrmiids -lksuser

PROJECT_BASENAME = krdstheora

include external/tp_stubz/Rules.lib.make
